import { ToolRegistry } from './ToolRegistry.ts';
import { AIContext, ToolCall } from '../types.ts';
import { ToolResult } from './types.ts';

export class ToolExecutor {
  constructor(private readonly toolRegistry: ToolRegistry) {}

  async executeCall(context: AIContext, toolCall: ToolCall): Promise<ToolResult> {
    const tool = this.toolRegistry.getTool(toolCall.name);
    
    if (!tool) {
      console.warn(`[ToolExecutor] Unknown tool requested: ${toolCall.name}`);
      return {
        status: "NOT_FOUND",
        message: `Tool '${toolCall.name}' is not recognized.`
      };
    }

    try {
      // Security Check: The arguments generated by Gemini are untrusted.
      // We pass `context` explicitly so the Tool uses safe server-side data
      // (like organizationId) instead of relying on Gemini's args.
      const args = toolCall.args || {};
      
      const result = await tool.execute(context, args);
      return result;
    } catch (error) {
      console.error(`[ToolExecutor] Tool execution failed for ${toolCall.name}:`, error);
      return {
        status: "ERROR",
        message: "Internal execution error."
      };
    }
  }
}
