/** @type {import('tailwindcss').Config} */
const config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}"
  ],
  theme: {
    extend: {
      screens: {
        'mobile': '768px',
        'tablet': '1024px',
        'laptop': '1280px',
        'desktop': '1440px',
      },
      spacing: {
        "unit": "4px",
        "stack-lg": "32px",
        "gutter": "16px",
        "stack-sm": "8px",
        "container-padding": "24px",
        "stack-md": "16px"
      },
      colors: {
        "on-tertiary-container": "#4d525a",
        "surface-container-low": "#1a1c1d",
        "error-container": "#93000a",
        "tertiary-fixed": "#dee2ec",
        "on-error-container": "#ffdad6",
        "surface-bright": "#37393b",
        "on-secondary-fixed": "#181c22",
        "primary-fixed": "#afecff",
        "error": "#ffb4ab",
        "outline-variant": "#3c494d",
        "surface-container": "#111415",
        "secondary-container": "#43474e",
        "primary-fixed-dim": "#14d8ff",
        "primary-container": "#00d8ff",
        "inverse-primary": "#00687b",
        "surface-tint": "#14d8ff",
        "outline": "#859398",
        "surface-dim": "#111415",
        "on-surface": "#e2e2e4",
        "on-secondary": "#2d3137",
        "inverse-surface": "#e2e2e4",
        "on-surface-variant": "#bbc9ce",
        "secondary-fixed": "#dfe2eb",
        "surface-variant": "#333537",
        "outline-subtle": "rgba(255, 255, 255, 0.08)",
        "surface-container-lowest": "#0c0e10",
        "surface-container-highest": "#333537",
        "background": "#0d1014",
        "secondary-fixed-dim": "#c3c6cf",
        "on-background": "#e2e2e4",
        "on-secondary-container": "#b2b5bd",
        "on-primary-fixed-variant": "#004e5d",
        "surface-container-high": "#282a2c",
        "on-primary-fixed": "#001f27",
        "tertiary": "#dee2ec",
        "on-tertiary-fixed": "#171c23",
        "inverse-on-surface": "#2f3132",
        "on-secondary-fixed-variant": "#43474e",
        "on-primary": "#003641",
        "tertiary-fixed-dim": "#c2c7d0",
        "tertiary-container": "#c2c6d0",
        "on-primary-container": "#005a6c",
        "on-tertiary-fixed-variant": "#42474f",
        "on-tertiary": "#2c3138",
        "on-error": "#690005",
        "secondary": "#c3c6cf",

        brand: {
          bg: '#13141B',
          sidebar: '#1A1C24',
          card: '#1C1F2A',
          border: '#2C303E',
          text: '#8B949E',
          textDark: '#E5E7EB',
          primary: '#8A5CFF',
          accent1: '#8A5CFF',
          accent2: '#418BFF',
          accent3: '#FACC15',
          accent4: '#10B981',
          accent5: '#06B6D4'
        },
        'ai-cyan': '#00F0FF',
        'ai-purple': '#8A2BE2',
        'ai-pink': '#FF00FF',
        'ai-blue': '#0055FF',
        'ai-dark': '#0B0C10',
        'ai-surface': '#121418',
        'ai-card': '#161920',
        
        // Ledger New Colors
        primary: 'var(--color-primary)',
        surface: 'var(--color-surface)',
        border: 'var(--color-border)',
        text: 'var(--color-text)',
        'text-muted': 'var(--color-text-muted)',
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        danger: 'var(--color-danger)',
        card: 'var(--color-card)',
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        'input': '14px',
        'button': '14px',
        'card': '20px',
        'modal': '24px',
        'badge': '999px',
        'full': '9999px',
      },
      boxShadow: {
        'neon-cyan': '0 0 15px rgba(0, 240, 255, 0.5)',
        'neon-purple': '0 0 20px rgba(138, 43, 226, 0.4)',
        'glass': '0 8px 32px 0 rgba(0, 0, 0, 0.37)',
        'xs': 'var(--shadow-xs)',
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'glow-primary': 'var(--glow-primary)',
        'glow-success': 'var(--glow-success)',
      },
      transitionDuration: {
        'fast': '120ms',
        'medium': '180ms',
        'slow': '280ms',
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-md": ["Geist", "monospace"],
        "mono-sm": ["Geist", "monospace"]
      },
      fontSize: {
        "display-lg": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-md": ["12px", { "lineHeight": "18px", "letterSpacing": "0", "fontWeight": "400" }],
        "headline-lg": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0", "fontWeight": "400" }],
        "body-sm": ["11px", { "lineHeight": "16px", "letterSpacing": "0", "fontWeight": "400" }],
        "headline-md": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-md": ["10px", { "lineHeight": "14px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "mono-sm": ["11px", { "lineHeight": "14px", "fontWeight": "400" }],
        
        // Ledger typography
        "page-title": ["32px", { fontWeight: "700" }],
        "section-title": ["20px", { fontWeight: "600" }],
        "card-title": ["15px", { fontWeight: "600" }],
        "body": ["14px", { fontWeight: "400" }],
        "label": ["12px", { fontWeight: "500" }],
        "muted": ["11px", { fontWeight: "400" }],
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'hero-glow': 'radial-gradient(circle at center, rgba(138, 43, 226, 0.15) 0%, rgba(0, 0, 0, 0) 70%)',
        'text-gradient': 'linear-gradient(to right, #00C8FF, #2B7FFF, #7B61FF)', // Keep our updated gradient
        'btn-gradient': 'linear-gradient(to right, #00F0FF, #0055FF)',
        'border-gradient': 'linear-gradient(to bottom right, rgba(255,255,255,0.2), rgba(255,255,255,0.05))',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float': 'float 6s ease-in-out infinite',
        'spin-slow': 'spin 8s linear infinite',
        'scan': 'scan 2s linear infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        scan: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100%)' },
        }
      }
    }
  }
};
module.exports = config;
